# Generated by Django 2.2.7 on 2019-11-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howTo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='related_to',
        ),
    ]
