# Generated by Django 2.2.7 on 2019-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howTo', '0002_remove_categorie_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
